### ISSUE TITLE
documentation errors

### ISSUE THREAD

**Issue by victorstewart** [aegis-aead/libaegis#1]
all the documentation in [src/include/aegis128l.h](src/include/aegis128l.h) claims 32 byte keys and nonces

```
 * npub: nonce input buffer (32 bytes)
 * k: key input buffer (32 bytes)
```

**Comment by jedisct1** [comment]
Thank you!

Yes, the comments are a copy of the AEGIS-256 comments, and I didn't pay attention to these differences. Thanks!
