### ISSUE TITLE
libaegis does not correctly detect CPU features when compiled for 32bit

### ISSUE THREAD

**Issue by Qriist** [aegis-aead/libaegis#13]
Hi! I'm not the one incorporating the library (that's @utelle) so I can't provide the nitty gritty but, basically, it's been discoverd that 32bit libaegis will always select AES. I figured I'd flag it for you since that seems like unintended behavior.

Here's the discussion on the matter.
https://github.com/utelle/SQLite3MultipleCiphers/issues/182#issuecomment-2519934974

Thanks in advance!

**Comment by jedisct1** [comment]
This is when using Visual Studio and targeting Win32, right?

Would you be able to check that `aegis_runtime_has_aesni()` and `aegis_runtime_has_avx()`  return?

**Comment by jedisct1** [comment]
You can try the following patch to enable AVX* instructions even when targeting x86.

But I don't know if all compilers are going to accept this.

```diff
diff --git a/src/common/common.h b/src/common/common.h
index f4d0aee..877f95d 100644
--- a/src/common/common.h
+++ b/src/common/common.h
@@ -25,8 +25,6 @@
 #    if defined(__clang__) || defined(__GNUC__)
 #        define HAVE_AVX_ASM
 #    endif
-#endif
-#if defined(__x86_64__) || defined(_M_AMD64)
 #    define HAVE_AVXINTRIN_H
 #    define HAVE_AVX2INTRIN_H
 #    define HAVE_AVX512FINTRIN_H
```

**Comment by utelle** [comment]
> You can try the following patch to enable AVX* instructions even when targeting x86.

I applied a similar patch. Works (see https://github.com/utelle/SQLite3MultipleCiphers/issues/182#issuecomment-2521721774).

> But I don't know if all compilers are going to accept this.

I don't know either. However, I will test with GCC under Linux (and maybe with MinGW64 under Windows).

**Comment by jedisct1** [comment]
The change was made in f5a77d4de3fc5ac7b676ed83c14ce022fa041059
